require("keymaps")
require("plugins")

require("plugins/lsp_config")
require("plugins/onedark_config")
require("plugins/lualine_config")
require("plugins/nvim-tree_config")
require("plugins/nvim-treesitter_config")
require("plugins/telescope_config")
require("plugins/none-ls_config")
require("plugins/completions_config")