modmap:
  - name: Global Modmap
    remap:
      CapsLock: Ctrl_L

keymap:
  - name: Toggle CapsLock state
    remap:
      Shift-F1: CapsLock

  - name: Ctrl+G to Esc except Emacs
    application:
      not:
        - emacs
    remap:
      C-g: Esc