require("keymaps")
require("plugins")

require("configs/lsp_config")
require("configs/onedark_config")
require("configs/lualine_config")
require("configs/nvim-tree_config")
require("configs/nvim-treesitter_config")
require("configs/telescope_config")
require("configs/none-ls_config")
require("configs/completions_config")
require("configs/autopairs_config")
require("configs/live_server_config")
require("configs/dadbod_config")
require("configs/noice_config")
require("configs/vim_tmux_navigator")
